name: Spring Boot CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]                                                                                                                                                                                                                                           name: Spring Boot CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: Windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'termurin'

    - name: Build project with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test

jobs:
  build:
    runs-on: Windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'termurin'

    - name: Build project with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test
